import type { Summary } from "./aggregate.js";

const usd = (v: number) => `$${v.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const n = (v: number) => v.toLocaleString("en-US");
const pct = (a: number, b: number) => (b > 0 ? ((a / b) * 100).toFixed(1) + "%" : "–");

/**
 * Client-deliverable audit report, generated from the same numbers the
 * terminal report shows. Findings are mechanical — each one is a threshold
 * check over measured data, never an opinion — so two people running the
 * audit on the same machine get the same report.
 */
export function auditReport(s: Summary, opts: { client: string; days: number | null }): string {
  const t = s.totals;
  const date = new Date().toISOString().slice(0, 10);
  const window = opts.days ? `last ${opts.days} days` : "full local history";
  const topRepo = s.byRepo[0];
  const topModel = s.byModel[0];
  const unpricedTotal = t.unpricedTokens;

  const findings: { level: "action" | "healthy" | "note"; title: string; body: string }[] = [];

  if (topRepo && t.cost > 0 && topRepo.cost / t.cost > 0.4) {
    findings.push({
      level: "action",
      title: `Spend is concentrated: ${topRepo.label} is ${pct(topRepo.cost, t.cost)} of everything`,
      body: `A single project consuming ${usd(topRepo.cost)} of ${usd(t.cost)} deserves a deliberate decision — either it is the priority and the budget is fine, or agent usage there needs guardrails (smaller scopes, lower-effort defaults for routine tasks). Today this concentration is invisible to every vendor dashboard.`,
    });
  }
  if (t.cacheWriteTokens > 0) {
    const r = s.cacheReuseRatio;
    if (r < 3) findings.push({
      level: "action",
      title: `Cache reuse is ${r.toFixed(1)}× — you pay to build context you rarely reuse`,
      body: `Cache writes bill at 1.25× the input rate and reads at 0.10×. Reuse below ~3× usually means many short one-shot sessions. Longer-lived sessions and resumed work convert 1.25×-rate tokens into 0.10×-rate tokens.`,
    });
    else findings.push({
      level: "healthy",
      title: `Cache reuse is ${r.toFixed(1)}× — healthy`,
      body: `Cached context is being re-read ${r.toFixed(1)} times per token written. No action needed; preserve current session habits.`,
    });
  }
  if (topModel && t.cost > 0 && topModel.cost / t.cost > 0.7) {
    findings.push({
      level: "note",
      title: `${topModel.label} carries ${pct(topModel.cost, t.cost)} of cost`,
      body: `Heavy reliance on one premium model is not wrong — but routine tasks (lint fixes, small edits, summaries) on a mid-tier model typically cut 20–40% of spend with no quality loss on those tasks. Worth one week of measured trial.`,
    });
  }
  if (unpricedTotal > 0) {
    findings.push({
      level: "note",
      title: `${n(unpricedTotal)} tokens belong to models with no confirmed public rate`,
      body: `These are counted but deliberately excluded from cost (${s.unpricedModels.join(", ")}). The true total is therefore higher than the headline. This tool never estimates a price it cannot source.`,
    });
  }
  if (s.commits.length > 0) {
    const ai = s.commits.reduce((a, c) => a + c.aiLinesAdded, 0);
    const hum = s.commits.reduce((a, c) => a + c.humanLinesAdded, 0);
    findings.push({
      level: "note",
      title: `Output side: ${pct(ai, ai + hum)} of scored added lines were agent-written`,
      body: `${n(s.commits.length)} commits scored by Cursor's local tracker. Pairing this with the spend above is the start of a cost-per-shipped-change metric.`,
    });
  }

  let md = `# AI Coding Spend Audit — ${opts.client}\n\n`;
  md += `*Prepared ${date} · window: ${window} · generated by spendwatch, 100% from local logs — no prompt or code content was read or transmitted.*\n\n`;
  md += `## Headline\n\n`;
  md += `| | |\n|---|---|\n`;
  md += `| **API-equivalent spend** | **${usd(t.cost)}** |\n`;
  md += `| Sessions / billed turns | ${n(s.sessions)} / ${n(t.turns)} |\n`;
  md += `| Agents observed | ${s.byVendor.map((v) => v.label).join(", ")} |\n`;
  md += `| Top project | ${topRepo ? `${topRepo.label} (${pct(topRepo.cost, t.cost)})` : "–"} |\n`;
  md += `| Top model | ${topModel ? `${topModel.label} (${pct(topModel.cost, t.cost)})` : "–"} |\n\n`;
  md += `> On subscription plans this figure is the list-price value extracted, not a bill — it is what the identical workload costs a team on API billing, and the honest basis for "is the subscription worth it".\n\n`;

  md += `## Findings\n\n`;
  const icon = { action: "🔴 ACT", healthy: "🟢 OK", note: "🟡 NOTE" } as const;
  for (const f of findings) md += `### ${icon[f.level]} — ${f.title}\n\n${f.body}\n\n`;

  md += `## Where the money goes\n\n### By project\n\n| project | spend | share |\n|---|---:|---:|\n`;
  for (const b of s.byRepo.slice(0, 10)) md += `| ${b.label} | ${usd(b.cost)} | ${pct(b.cost, t.cost)} |\n`;
  md += `\n### By model\n\n| model | spend | share |\n|---|---:|---:|\n`;
  for (const b of s.byModel.slice(0, 10)) md += `| ${b.label} | ${usd(b.cost)} | ${pct(b.cost, t.cost)} |\n`;

  md += `\n## Method\n\nToken counts come from the agents' own local logs (Claude Code transcripts, Codex rollouts, Copilot session DB, Cursor commit scores). Costs apply published list prices — dated and source-attributed in the open-source rate table — with cache writes at 1.25× and cache reads at 0.10× the input rate where the vendor bills that way. Unknown models are never priced by guesswork. Duplicate turns from resumed sessions are removed by request id.\n`;
  return md;
}
